name: Build Skia

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: skia

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Sync dependencies
        run: |
          python skia/tools/git-sync-deps
        shell: pwsh
        working-directory: skia

      - name: Generate cmake files
        run: |
          bin/gn gen out/config --ide=json --json-ide-script=../../gn/gn_to_cmake.py
        shell: pwsh
        working-directory: skia

      - name: Commit and push compressed file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add compressed skia artifact"
          git push
        shell: pwsh
        working-directory: skia
        env:
          GITHUB_TOKEN: ${{ secrets.tk }}
